In [1]:
import numpy as np

In [2]:
l = [5,9,3,7,4]
list=np.array(l)

In [3]:
list

array([5, 9, 3, 7, 4])

In [4]:
type(list)

numpy.ndarray

In [5]:
list[-2]

7

In [6]:
list[2:4]

array([3, 7])

In [7]:
l2 = ([1,2,3],[4,5,6],[7,8,9])
list2 = np.array(l2)

In [8]:
list2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
len(list)

5

In [10]:
len(list2)

3

In [11]:
np.arange(15,30,3)

array([15, 18, 21, 24, 27])

In [13]:
x = np.zeros((5,4,3))

In [14]:
np.ones((4,3,2))*3-1

array([[[2., 2.],
        [2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.],
        [2., 2.]]])

In [15]:
x

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
x.shape

(5, 4, 3)

In [20]:
x[3,3,2]=99

In [21]:
x

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0., 99.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [23]:
x.flatten()

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 99.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [26]:
x = x.reshape((10,6))

In [27]:
x

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 99.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [30]:
y = np.zeros((3,2,2))

In [31]:
y

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [34]:
y = np.arange(12).reshape((6,2))

In [35]:
y

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.sqrt(4225)

65.0

In [38]:
y.mean()

5.5

In [39]:
y.mean(axis=1)

array([ 0.5,  2.5,  4.5,  6.5,  8.5, 10.5])

In [40]:
y.std()

3.452052529534663

In [41]:
y.var()

11.916666666666666

In [42]:
np.sin(np.arange(9))

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [43]:
np.random.seed(5)

In [44]:
np.random.randint(0,40,(8,5))

array([[35, 14, 38, 16,  9],
       [ 8, 36, 39, 27, 30],
       [16,  7, 12, 15, 39],
       [16, 27, 13, 11,  1],
       [30, 20, 22, 18,  9],
       [ 1, 18, 39, 16, 14],
       [ 5,  0, 16,  4, 36],
       [27, 31,  2,  4, 38]])

In [45]:
z = np.arange(20)

In [46]:
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [47]:
np.random.shuffle(z)

In [48]:
z

array([ 0,  2,  5, 15, 19,  6,  8, 10, 16,  1,  3, 14, 11, 13, 12,  4,  7,
       17, 18,  9])

In [49]:
np.min(z)

0

In [50]:
np.max(z)

19

In [51]:
np.argmin(z)

0

In [52]:
np.argmax(z)

4

In [53]:
x = np.linspace(0,10,50)

In [54]:
x

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])